### ISSUE TITLE
Application freezes with Koamtac

### ISSUE THREAD

**Issue by johnposten** [DataSplice/KoamTacScanner#12]
per @randymcdaniel .  We were able to replicate this in house by logging into demorandy.datasplice.com as ross / password.
I am using the koamtac scanner with the Samsung tablet.  When I go to hardware in the application settings and select Koamtac it connects to the scanner (the scanner beeps saying it is paired), it leaves the Driver Name as Intent Scanner and completely freezes the Datasplice application. This does not happen with the IPad.  Also if you attempt to login with this scanner selected it will also beep and then freeze the application.

**Comment by WebeWizard** [comment]
Hmmm.... It works fine when using a debug version of the app, but adding the --release flag causes the behavior above.   Will probably be pretty difficult to track down, but I'm guessing it has something to do with the current version of crosswalk plugin.

**Comment by WebeWizard** [comment]
I believe this was fixed by upgrading the koamtac sdk.
