### ISSUE TITLE
Enabling KoamTacScanner on Android 6.0.1 will freeze app

### ISSUE THREAD

**Issue by WebeWizard** [DataSplice/KoamTacScanner#13]
It looks like creating the KDCReader object is hanging.

The solution seems to be upgrading the KoamTac SDK.    Reaching out to them for the latest library, then I think we'll be good to go.

**Comment by c-riess** [comment]
This doesn't appear to be fixed for Android devices on Marshmallow (6.0.1).

1.  Connect KoamTac scanner to the device through SPP pairing.
2.  In DataSplice, Settings > Hardware > select KoamTac
3.  Client freezes and eventually crashes.

Using the forms client at least presents an error, 
![image](https://user-images.githubusercontent.com/19620596/27349371-33ccc0f6-55b4-11e7-8fec-5a6814d16d1b.png)

**Comment by WebeWizard** [comment]
Probably the same non-sense as last time, where it works fine in debug builds but not in release :P

**Comment by WebeWizard** [comment]
Somehow I was able to past the hang. I think it has to do with wether or not the koamtac is paired correctly.

**Comment by WebeWizard** [comment]
worked for me an android 6.0 device and an android 6.0.1 device

**Comment by stephen-williams-datasplice** [comment]
On current app store version?

**Comment by WebeWizard** [comment]
Chris' comment above was because the app-store version of datasplice didn't have the fix in it, not that it wasn't fixed in the master build of the plugin.
