### ISSUE TITLE
Use with Ionic

### ISSUE THREAD

**Issue by irishChip** [DataSplice/KoamTacScanner#5]
Great plugin, thanks to all contributors.
I am trying to integrate it with an Ionic app on an Android device. I wrote a separate ngCordova module to utilize the plugin, following the batteryStatus ngCordova module as a template. The problem I'm having is figuring out how to listen for hardware button pushes on the KoamTac scanner in the Ionic app. The README says that after an 'enable' call succeeds, all subsequent scans will result in a call to <code>onScan</code>. I added a <code>$window.addEventListener()</code> for both <code>onScan</code> and <code>trigger</code> in my controller, but hardware button pushes are not getting picked up.
Any insight would be appreciated.

Thanks.

[ngCordova-wrapper.txt](https://github.com/DataSplice/KoamTacScanner/files/122026/ngCordova-wrapper.txt)

**Comment by WebeWizard** [comment]
It doesn't look like you're passing the required callbacks into enable function.
See: https://github.com/DataSplice/KoamTacScannerApp/blob/master/www/js/index.js#L63

Pass your onScan callback as a parameter of enable(), that way you can receive results from scans.

**Comment by irishChip** [comment]
@WebeWizard , thank you, that got me down the right path. Removed all the <code>$window.addEventListener()</code>'s and added in the callback function to the <code>enable</code> was the key.
